---
permalink: windows/concept_restoring_database_backup.html 
sidebar: sidebar 
keywords: oracle, enable, restore, database, snapshot, restoring, backup, mean-time-to-recovery, mttr 
summary: 通过 SnapManager for Oracle ，您可以将数据库还原到创建 Snapshot 副本时的状态。由于备份的创建频率更高，因此需要应用的日志数量会减少，从而减少数据库的平均恢复时间（ MTTR ）。 
---
= 还原数据库备份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 SnapManager for Oracle ，您可以将数据库还原到创建 Snapshot 副本时的状态。由于备份的创建频率更高，因此需要应用的日志数量会减少，从而减少数据库的平均恢复时间（ MTTR ）。

以下是与还原和恢复数据库中的数据相关的一些任务：

* 执行基于文件的还原。
* 还原整个备份或其中一部分。
+
如果要还原其中一部分，请指定一组表空间或一组数据文件。您还可以还原控制文件以及数据，或者仅还原控制文件本身。

* 根据时间点或所有可用日志恢复数据，这些日志存储提交到数据库的最后一个事务。
+
时间点可以是 Oracle 系统更改编号（ SCN ）或日期和时间（ yyyy-mm-dd ： hh ： mm ： ss ）。SnapManager 使用 24 小时制时钟。

* 从主存储（本地备份）上的备份还原。
* 使用 SnapManager 还原和恢复备份，或者使用 SnapManager 还原备份，然后使用恢复管理器（ RMAN ）等其他工具恢复数据。
* 从备用位置还原备份。


有关详细信息，请参见 _Oracle SnapManager 最佳实践 _ 。

您可以使用 SnapManager 3.0 及更高版本还原以前版本的 SnapManager 所做的备份。

管理员可以使用 SnapManager 图形用户界面（ GUI ）或命令行界面（ CLI ）执行还原或恢复操作。

* 相关信息 *

xref:concept_database_backup_management.adoc[备份数据库]

xref:reference_the_smosmsapbackup_restore_command.adoc[smo backup restore 命令]

http://media.netapp.com/documents/tr-3761.pdf["SnapManager for Oracle 最佳实践： media.netapp.com/documents/tr-3761.pdf"]
