---
permalink: windows/concept_variables_available_in_custom_script_for_restore_operation.html 
sidebar: sidebar 
keywords: provide, context, information, form, environment, variable, restore, operation, perform, backup 
summary: SnapManager 以与正在执行的还原操作相关的环境变量的形式提供上下文信息。例如，您的脚本可以检索原始主机的名称以及所还原备份的标签。 
---
= 可用于还原操作的任务脚本中的变量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 以与正在执行的还原操作相关的环境变量的形式提供上下文信息。例如，您的脚本可以检索原始主机的名称以及所还原备份的标签。

下表列出了可在脚本中使用的环境变量：

|===
| 变量 | Description | 格式。 


 a| 
sm_operation_ID
 a| 
指定当前操作的 ID
 a| 
string



 a| 
sm_profile_name
 a| 
指定所用配置文件的名称
 a| 
string



 a| 
sm_host
 a| 
指定数据库的主机名
 a| 
string



 a| 
sm_os_user
 a| 
指定数据库的操作系统（ OS ）所有者
 a| 
string



 a| 
sm_os_Group
 a| 
指定数据库的操作系统组
 a| 
string



 a| 
sm_backup_type
 a| 
指定备份的类型（联机，脱机或自动）
 a| 
string



 a| 
sm_backup_label
 a| 
指定备份标签
 a| 
string



 a| 
sm_backup_ID
 a| 
指定备份 ID
 a| 
string



 a| 
sm_backup_profile
 a| 
指定用于备份的配置文件
 a| 
string



 a| 
sm_recovery_type
 a| 
指定恢复配置信息
 a| 
string



 a| 
sm_volume_restore_mode
 a| 
指定卷还原配置
 a| 
string



 a| 
sm_target_filer_name
 a| 
指定目标存储系统名称 * 注： * 如果使用多个存储系统，则存储系统名称必须用逗号分隔。
 a| 
string



 a| 
sm_target_volume_name
 a| 
指定目标卷名称 * 注： * 目标卷名称必须以存储设备名称作为前缀，例如 sm_target_filer_name/sm_target_volume_name 。
 a| 
string



 a| 
sm_host_file_system
 a| 
指定主机文件系统
 a| 
string



 a| 
sm_snapshot_names
 a| 
指定 Snapshot 列表 * 注： * Snapshot 副本的名称必须以存储系统名称和卷名称作为前缀。Snapshot 副本的名称以逗号分隔。
 a| 
string array



 a| 
sm_archive_logs_directory
 a| 
指定归档日志目录 * 注： * 如果归档日志位于多个目录中，则这些目录的名称以逗号分隔。
 a| 
string array



 a| 
sm_redo 日志目录
 a| 
指定重做日志目录 * 注： * 如果重做日志位于多个目录中，则这些目录的名称以逗号分隔。
 a| 
string array



 a| 
sm_control_files_directory
 a| 
指定控制文件目录 * 注： * 如果控制文件位于多个目录中，则这些目录的名称以逗号分隔。
 a| 
string array



 a| 
sm_data_files_directory
 a| 
指定数据文件目录 * 注： * 如果数据文件位于多个目录中，则这些目录的名称以逗号分隔。
 a| 
string array

|===