---
permalink: windows/reference_error_messages.html 
sidebar: sidebar 
keywords: error, message, information, operation 
summary: 您可以找到有关与不同 SnapManager 操作关联的错误消息的信息。 
---
= 错误消息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以找到有关与不同 SnapManager 操作关联的错误消息的信息。



== 最常见的错误消息

下表列出了与 SnapManager for Oracle 关联的一些最常见且最重要的错误：

|===


| 错误消息 | 说明 | 解决方法： 


 a| 
SD-10038 ：文件系统不可写。
 a| 
SnapManager 进程不具有对文件系统的写入访问权限。
 a| 
您必须确保 SnapManager 进程对文件系统具有写入访问权限。更正此错误后，您可能需要创建另一个快照。



 a| 
SMO-05075 ：无法创建配置文件。您必须正确配置 DP/XDP 关系，或者根据底层关系选择正确的保护策略。
 a| 
底层卷不处于 SnapVault 或 SnapMirror 关系中。
 a| 
您必须在源卷和目标卷之间配置数据保护关系并初始化此关系。



 a| 
SMO-0503 ：您已为此配置文件指定相同的名称。指定其他名称以重命名配置文件。
 a| 
名称相同的配置文件不能位于存储库中。
 a| 
请提供未使用的配置文件名称。



 a| 
SMO-0505 ：无法更新数据集元数据。
 a| 
数据集可能已删除或不存在。
 a| 
在更新数据集元数据之前，请使用 NetApp 管理控制台验证数据集是否存在。



 a| 
SMO-0556 ：无法更新此配置文件，因为此配置文件正在运行操作。您必须等待操作完成，然后再更新配置文件。
 a| 
执行备份，还原和克隆操作时，无法更新配置文件。
 a| 
完成当前操作后更新配置文件。



 a| 
SMO-05509 ： archivelog 主保留期限无效 - 指定正整数值。
 a| 
归档日志备份的保留期限不能为负数。
 a| 
为归档日志备份的保留期限指定一个正值。



 a| 
SMO-074663 ：此备份还原要求数据库处于所需状态。无法将数据库置于所需状态。
 a| 
数据库未处于备份操作所需的状态。
 a| 
在创建备份副本之前，请检查数据库是否处于相关状态。要还原的数据库的状态取决于要执行的还原过程的类型以及要包含的文件类型。



 a| 
SMO-09315 ：执行存储库升级或更新操作后，除非使用通知主机详细信息更新摘要通知，否则您可能无法收到先前版本中设置的通知的摘要通知。
 a| 
滚动升级后，系统不会为此存储库配置通知设置。
 a| 
滚动升级后，更新摘要通知设置以接收通知。



 a| 
SM0-2076 ：标签名称不应包含除下划线以外的任何特殊字符。
 a| 
标签名称包含除下划线以外的其他特殊字符。
 a| 
标签名称在配置文件中必须是唯一的。此名称可以包含字母，数字，下划线（ _ ）和连字符（ - ）（但不能以连字符开头）。确保标签不包含除下划线以外的任何特殊字符。



 a| 
SMO-06308 ：尝试启动计划时出现异常： java.lang.NullPointerException
 a| 
配置配置文件主机的完全限定域名（ FQDN ）而不是系统的主机名，并且无法解析配置文件主机的 FQDN 。
 a| 
请确保使用系统的主机名，而不是 FQDN 。



 a| 
ExecuteRestoreSteps 中的故障： ORACLE-10003 ：针对 Oracle 数据库 +ASM1 执行 SQL "drop diskgroup ； control diskgroup name ； including contents" 时出错： ora-15039 ： diskgroup not dropped ORA-15027 ： active use of diskgroup ； "control diskgroup name； " dismount
 a| 
使用控制文件还原备份的操作无法删除控制磁盘组。如果控制磁盘组中备份的控制文件已过时，则会发生此问题描述。
 a| 
确定已备份的陈旧控制文件并手动将其删除。



 a| 
RMAN-06004 ：恢复目录数据库中的 Oracle 错误： ora-01424 ：转义字符后面缺少字符或字符非法
 a| 
如果 SnapManager 与 RMAN 集成，则备份创建操作无法从目录中删除备份副本。
 a| 
检查是否存在用于从 RMAN 删除备份的外部脚本。在 RMAN 中执行交叉检查备份命令以更新 RMAN 存储库，并执行 resync catalog 命令以将目标数据库的控制文件与恢复目录同步。



 a| 
[debug] ：修剪备份时出现异常。java.lang.IllegalStateException ： [Assertion failed] —此状态不可变必须为 true
 a| 
系统会为一个操作 ID 创建多个 Snapshot 副本。
 a| 
手动删除 Snapshot 副本并使用脚本从存储库中删除条目。



 a| 
SnapManager 在日志文件中显示的系统时间和时间不匹配或不同步。
 a| 
Java 7 尚不支持更改时区。
 a| 
应用 Oracle 提供的 tzupdateer 修补程序。



 a| 
dis磁盘 -00001 ：无法发现存储：以下标识符不存在或不是预期类型： ASM File
 a| 
数据或控制文件或重做日志会在 ASM 数据库中进行多路传输。
 a| 
删除 Oracle 多路复用。



 a| 
ora-01031 ：权限不足。验证 SnapManager Windows 服务是否已设置为以具有正确权限的用户身份运行，并且用户是否包含在 ORA_DBA 组中。
 a| 
您在 SnapManager 中的权限不足。SnapManager 服务帐户不属于 ORA_DBA 组。
 a| 
右键单击桌面上的 * 计算机 * 图标并选择 * 管理 * 以验证 SnapManager 服务的用户帐户是否属于 ORA_DBA 组。检查本地用户和组，并确保此帐户属于 ORA_DBA 组。如果此用户是本地管理员，请确保此用户位于组中，而不是域管理员中。



 a| 
0001-SMO-02016 ：在此备份操作中，数据库中可能存在未备份的外部表（因为在此备份期间数据库未打开，因此无法查询 all_external_locations 以确定是否存在外部表）。
 a| 
SnapManager 不会备份外部表（例如，不存储在 .dbf 文件中的表）。之所以出现此问题描述，是因为备份期间未打开数据库， SnapManager 无法确定是否正在使用任何外部表。
 a| 
在此操作中，数据库中可能存在未备份的外部表（因为数据库在备份期间未打开）。



 a| 
0002-332 管理员错误：无法检查对卷 "volume_name" 的 sd.snapshot.Clone 访问权限，以查找 Operations Manager 服务器 "DFM_server" 上的用户用户名。原因：指定的资源无效。在 Operations Manager 服务器 "DFM_server" 上找不到其 ID
 a| 
未设置正确的访问权限和角色。
 a| 
为尝试执行命令的用户设置访问权限或角色。



 a| 
【警告】 flow-11011 ：操作中止了【错误】 flow-11-8 ：操作失败： Java 堆空间。
 a| 
数据库中的归档日志文件数量超过允许的最大数量。
 a| 
. 导航到 SnapManager 安装目录。
. 打开 launch Java 文件。
. 增加 `java -Xmx160m` java heap space 参数的值。例如，您可以将此值从默认值 160 米修改为 200 米，并将其修改为 `java -Xmx200 米` 。




 a| 
SMO-21019 ：对目标： "e ： \dest" 执行归档日志删减失败，原因： "Oracle-00101 ：执行 RMAN 命令时出错：【删除 NOPROMPT ARCHIVELOG 'E ： \dest]]
 a| 
在其中一个目标中，归档日志修剪失败。在这种情况下， SnapManager 会继续从其他目标对归档日志文件进行修剪。如果从活动文件系统手动删除任何文件， RMAN 将无法从该目标对归档日志文件进行修剪。
 a| 
从 SnapManager 主机连接到 RMAN 。运行 RMAN Crosscheck ARCHIVELOG ALL 命令，然后重新对归档日志文件执行修剪操作。



 a| 
SMO-13032 ：无法执行操作：归档日志 Prune.根发生原因： RMAN 异常： ORACLE-00101 ：执行 RMAN 命令时出错。
 a| 
归档日志文件将从归档日志目标位置手动删除。
 a| 
从 SnapManager 主机连接到 RMAN 。运行 RMAN Crosscheck ARCHIVELOG ALL 命令，然后重新对归档日志文件执行修剪操作。



 a| 
无法解析 Shell 输出：（ java.util.regex.Matcher[pattern=Command complete 。Region = 0 ， 18 lastmatch=] ）不匹配（名称： backup_script ）无法解析 Shell 输出：（ java.util.regex.Matcher[pattern=Command complete 。Region = 0 ， 25 lastmatch=] ）不匹配（说明：备份脚本）

无法解析 Shell 输出：（ java.util.regex.Matcher[pattern=Command complete 。Region = 0.9 lastmatch=] ）不匹配（超时： 0 ）
 a| 
未在任务前或任务后脚本中正确设置环境变量。
 a| 
检查任务前或任务后脚本是否遵循标准 SnapManager 插件结构。有关追加信息在脚本中使用环境变量的信息，请参见 xref:concept_operations_in_task_scripts.adoc[任务脚本中的操作]。



 a| 
ORA-01450 ：已超出最大密钥长度（ 6398 ）。
 a| 
在从适用于 Oracle 的 SnapManager 3.2 升级到适用于 Oracle 的 SnapManager 3.3 时，升级操作将失败并显示此错误消息。之所以出现此问题描述，可能是因为以下原因之一：

* 存储库所在表空间的块大小小于 8k 。
* NLS_LENG_semantictics 参数设置为 char 。

 a| 
您必须将这些值分配给以下参数：

* block_size=8192
* NLS_LENG=byte


修改参数值后，必须重新启动数据库。

有关详细信息，请参见知识库文章 2017632 。

|===


== 与数据库备份过程（ 2000 系列）关联的错误消息

下表列出了与数据库备份过程相关的常见错误：

|===


| 错误消息 | 说明 | 解决方法： 


 a| 
SMO-02066 ：您无法删除或释放归档日志备份 "data-logs" ，因为备份与数据备份 "data-logs" 关联。
 a| 
归档日志备份与数据文件备份一起进行，您尝试删除归档日志备份。
 a| 
使用 -force 选项删除或释放备份。



 a| 
SMO-02067 ：您不能删除或释放归档日志备份 "data-logs" ，因为备份与数据备份 "data-logs" 关联且处于分配的保留期限内。
 a| 
归档日志备份与数据库备份关联且处于保留期限内，您尝试删除归档日志备份。
 a| 
使用 -force 选项删除或释放备份。



 a| 
SMO-07142 ：由于排除模式 <exclude> 模式，已排除归档日志。
 a| 
您可以在配置文件创建或备份创建操作期间排除某些归档日志文件。
 a| 
无需执行任何操作。



 a| 
SMO-07155 ：活动文件系统中不存在 <count> 个归档日志文件。这些归档的日志文件不会包含在备份中。
 a| 
在配置文件创建或备份创建操作期间，活动文件系统中不存在归档日志文件。这些归档的日志文件不会包含在备份中。
 a| 
无需执行任何操作。



 a| 
SMO-07148 ：归档的日志文件不可用。
 a| 
在配置文件创建或备份创建操作期间，不会为当前数据库创建任何归档日志文件。
 a| 
无需执行任何操作。



 a| 
SMO-07150 ：未找到归档的日志文件。
 a| 
文件系统中缺少所有归档日志文件，或者在配置文件创建或备份创建操作期间将其排除。
 a| 
无需执行任何操作。



 a| 
SMO-13032 ：无法执行操作：备份创建。根发生原因： ORACLE-20001 ：尝试将数据库实例 dfcln1 的状态更改为 OPEN 时出错： ORACLE-20004 ：希望能够在不使用 RESETLOGS 选项的情况下打开数据库，但 Oracle 报告需要使用 RESETLOGS 选项打开数据库。为了防止意外重置日志，此过程不会继续。请确保可以在不使用 RESETLOGS 选项的情况下打开数据库，然后重试。
 a| 
您尝试备份使用 -no-resetlogs 选项创建的克隆数据库。克隆的数据库不是完整的数据库。但是，您可以对克隆的数据库执行 SnapManager 操作，例如创建配置文件和备份等，但由于克隆的数据库未配置为完整的数据库， SnapManager 操作将失败。
 a| 
恢复克隆的数据库或将数据库转换为 Data Guard 备用数据库。

|===


== 与还原过程相关的错误消息（ 3000 系列）

下表显示了与还原过程相关的常见错误：

|===


| 错误消息 | 说明 | 解决方法： 


 a| 
SMO-03031 ：还原备份 <variable> 需要使用还原规范，因为备份的存储资源已释放。
 a| 
您尝试还原已释放其存储资源的备份，但未指定还原规范。
 a| 
指定还原规范。



 a| 
SMO-03032 ：还原规范必须包含要还原的文件的映射，因为备份的存储资源已释放。需要映射的文件为： <variable> from Snapshots ： <variable>
 a| 
您尝试还原已释放其存储资源的备份以及不包含要还原的所有文件的映射的还原规范。
 a| 
更正还原规范文件，使映射与要还原的文件匹配。



 a| 
ORACLE-30028 ：无法转储日志文件 <filename> 。此文件可能缺失 / 无法访问 / 已损坏。此日志文件不会用于恢复。
 a| 
无法使用联机重做日志文件或归档日志文件进行恢复。发生此错误的原因如下：

* 错误消息中提及的联机重做日志文件或归档日志文件没有足够的更改编号可用于恢复。如果数据库联机而未进行任何事务，则会发生这种情况。重做日志或归档日志文件没有任何可应用于恢复的有效变更编号。
* 错误消息中提及的联机重做日志文件或归档日志文件没有足够的 Oracle 访问权限。
* 错误消息中提及的联机重做日志文件或归档日志文件已损坏， Oracle 无法读取。
* 在所述路径中未找到错误消息中提及的联机重做日志文件或归档日志文件。

 a| 
如果错误消息中提及的文件是归档日志文件，并且您手动提供了恢复功能，请确保该文件具有对 Oracle 的完全访问权限。即使该文件具有完全权限， 此消息仍会显示，归档日志文件没有任何要应用于恢复的更改编号，可以忽略此消息。

|===


== 与克隆进程（ 4000 系列）关联的错误消息

下表显示了与克隆过程相关的常见错误：

|===


| 错误消息 | 说明 | 解决方法： 


 a| 
SMO-04133 ：转储目标不能存在
 a| 
您正在使用 SnapManager 创建新克隆；但是，新克隆要使用的转储目标已存在。如果存在转储目标，则 SnapManager 无法创建克隆。
 a| 
在创建克隆之前，请删除或重命名旧的转储目标。



 a| 
SMO-13032 ：无法执行操作： clone Create 。根发生原因： ORACLE-001 ：执行 SQL 时出错： [alter database open RESETLOGS ； ] 。返回的命令： ora-38856 ：无法将实例 unn命名 实例 _2 （重做线程 2 ）标记为已启用。
 a| 
使用以下设置从备用数据库创建克隆时，克隆创建将失败：

* 使用 RMAN 创建备份数据文件的备用。

 a| 
在创建克隆之前，在克隆规范文件中添加 _no_recovery_through _resetlogs=true 参数。请参见适用于追加信息的 Oracle 文档（ ID 334899.1 ）。确保您已获得 Oracle Metalink 用户名和密码。



 a| 
 a| 
您未在克隆规范文件中为参数提供值。
 a| 
您必须为此参数提供一个值，或者如果克隆规范文件中不需要该参数，则必须将其删除。

|===


== 与管理配置文件进程（ 5000 系列）关联的错误消息

下表显示了与克隆过程相关的常见错误：

|===


| 错误消息 | 说明 | 解决方法： 


 a| 
SMO-20600 ：在存储库 "repo_name" 中未找到配置文件 "profile1" 。请运行 " 配置文件同步 " 以更新配置文件到存储库的映射。
 a| 
如果配置文件创建失败，则无法执行转储操作。
 a| 
使用 smsystem dump 。

|===


== 与释放备份资源相关的错误消息（备份 6000 系列）

下表显示了与备份任务相关的常见错误：

|===


| 错误消息 | 说明 | 解决方法： 


 a| 
SMO-06030 ：无法删除备份，因为它正在使用中： <variable>
 a| 
您尝试使用命令执行无备份操作，在备份已挂载，具有克隆或标记为无限制保留时执行此操作。
 a| 
卸载备份或更改无限保留策略。如果存在克隆，请将其删除。



 a| 
SMO-06045 ：无法释放备份 <variable> ，因为备份的存储资源已释放
 a| 
当备份已释放时，您尝试使用命令执行备份可用操作。
 a| 
如果备份已释放，则无法释放它。



 a| 
SMO-06047 ：只能释放成功的备份。备份 <ID> 的状态为 <status> 。
 a| 
当备份状态不成功时，您尝试使用命令执行备份可用操作。
 a| 
成功备份后重试。



 a| 
SMO-13082 ：无法对备份 <ID> 执行操作 <variable> ，因为备份的存储资源已释放。
 a| 
您尝试使用命令挂载已释放存储资源的备份。
 a| 
您不能挂载，克隆或验证已释放存储资源的备份。

|===


== 与滚动升级过程（ 9000 系列）相关的错误消息

下表显示了与滚动升级过程相关的常见错误：

|===


| 错误消息 | 说明 | 解决方法： 


 a| 
SMO-09234 ：旧存储库中不存在以下主机。< 主机名 > 。
 a| 
您尝试执行主机滚动升级，而先前的存储库版本不存在此升级。
 a| 
使用 SnapManager CLI 早期版本中的 repository show-repository 命令检查主机是否位于先前的存储库中。



 a| 
SMO-09255 ：新存储库中不存在以下主机。< 主机名 > 。
 a| 
您尝试执行主机回滚，新存储库版本中不存在此主机。
 a| 
在更高版本的 SnapManager 命令行界面中使用 repository show-repository 命令检查主机是否位于新存储库中。



 a| 
SMO-09256 ：不支持回滚，因为指定主机 <hostname> 存在新的配置文件 <proFiles>.. 。
 a| 
您已尝试回滚包含存储库中现有新配置文件的主机。但是，早期 SnapManager 版本的主机中不存在这些配置文件。
 a| 
在回滚之前，删除较新版本或已升级版本的 SnapManager 中的新配置文件。



 a| 
SMO-09257 ：不支持回滚，因为备份 <backupid> 已挂载到新主机中。
 a| 
您尝试回滚已挂载备份的较高版本 SnapManager 主机。这些备份不会挂载在早期版本的 SnapManager 主机中。
 a| 
卸载较高版本的 SnapManager 主机中的备份，然后执行回滚。



 a| 
SMO-09258 ：不支持回滚，因为备份 <backupid> 已卸载到新主机中。
 a| 
您尝试回滚包含正在卸载的备份的较高版本 SnapManager 主机。
 a| 
在更高版本的 SnapManager 主机中挂载备份，然后执行回滚。



 a| 
SMO-09298 ：无法更新此存储库，因为它已在更高版本中具有其他主机。请改为对所有主机执行滚动升级。
 a| 
您对单个主机执行了滚动升级，然后更新了该主机的存储库。
 a| 
对所有主机执行滚动升级。



 a| 
SMO-09297 ：启用约束时出错。存储库可能处于不一致状态。建议还原您在当前操作之前所做的存储库备份。
 a| 
如果存储库数据库处于不一致状态，则您尝试执行滚动升级或回滚操作。
 a| 
还原先前备份的存储库。

|===


== 执行操作（ 12 ， 000 系列）

下表显示了与操作相关的常见错误：

|===


| 错误消息 | 说明 | 解决方法： 


 a| 
SMO-12347 [ 错误 ] ： SnapManager 服务器未在主机 < 主机 > 和端口 < 端口 > 上运行。请在运行 SnapManager 服务器的主机上运行此命令。
 a| 
在设置配置文件时，您输入了有关主机和端口的信息。但是， SnapManager 无法执行这些操作，因为 SnapManager 服务器未在指定的主机和端口上运行。
 a| 
在运行 SnapManager 服务器的主机上输入命令。您可以使用 lsnrctl status 命令检查端口，并查看运行数据库的端口。如果需要，可在 backup 命令中更改端口。

|===


== 执行流程组件（ 13 ， 000 系列）

下表显示了与 SnapManager 的进程组件相关的常见错误：

|===


| 错误消息 | 说明 | 解决方法： 


 a| 
SMO-13083 ：值为 "x" 的 Snapname 模式包含字母，数字，下划线，短划线和花括号以外的字符。
 a| 
在创建配置文件时，您自定义了 Snapname 模式；但是，您包含了不允许使用的特殊字符。
 a| 
删除字母，数字，下划线，短划线和花括号以外的特殊字符。



 a| 
SMO-13084 ：值为 "x" 的 Snapname 模式不包含相同数量的左括号和右括号。
 a| 
创建配置文件时，您自定义了 Snapname 模式；但是，左括号和右括号不匹配。
 a| 
在 Snapname 模式中输入匹配的括号和右括号。



 a| 
SMO-13085 ：值为 "x" 的 Snapname 模式包含无效变量名 "y" 。
 a| 
在创建配置文件时，您自定义了 Snapname 模式；但是，您包含了一个不允许的变量。
 a| 
删除有问题的变量。要查看可接受变量的列表，请参见 xref:concept_snapshot_copy_naming.adoc[Snapshot 副本命名]。



 a| 
值为 "x" 的 SMO-13086 Snapname 模式必须包含变量 "smID" 。
 a| 
在创建配置文件时，您自定义了 Snapname 模式；但是，您省略了所需的 SMID 变量。
 a| 
插入所需的 SMID 变量。

|===


== 与 SnapManager 实用程序（ 14 ， 000 系列）关联的错误消息

下表显示了与 SnapManager 实用程序相关的常见错误：

|===


| 错误消息 | 说明 | 解决方法： 


 a| 
SMO-14501 ：邮件 ID 不能为空。
 a| 
您未输入电子邮件地址。
 a| 
输入有效的电子邮件地址。



 a| 
SMO-14502 ：邮件主题不能为空。
 a| 
您未输入电子邮件主题。
 a| 
输入相应的电子邮件主题。



 a| 
SMO-14506 ：邮件服务器字段不能为空。
 a| 
您未输入电子邮件服务器主机名或 IP 地址。
 a| 
输入有效的邮件服务器主机名或 IP 地址。



 a| 
SMO-14507 ：邮件端口字段不能为空。
 a| 
您未输入电子邮件端口号。
 a| 
输入电子邮件服务器端口号。



 a| 
SMO-14508 ：发件人邮件 ID 不能为空。
 a| 
您未输入发件人的电子邮件地址。
 a| 
输入有效的发件人电子邮件地址。



 a| 
SMO-14509 ：用户名不能为空。
 a| 
您启用了身份验证，但未提供用户名。
 a| 
输入电子邮件身份验证用户名。



 a| 
SMO-14510 ：密码不能为空。请输入密码。
 a| 
您已启用身份验证，但未提供密码。
 a| 
输入电子邮件身份验证密码。



 a| 
SMO-14550 ：电子邮件状态 < 成功 / 失败 > 。
 a| 
端口号，邮件服务器或接收方的电子邮件地址无效。
 a| 
在电子邮件配置期间提供正确的值。



 a| 
SMO-14559 ：发送电子邮件通知失败： <error> 。
 a| 
这可能是由于端口号无效，邮件服务器无效或收件人的邮件地址无效所致。
 a| 
在电子邮件配置期间提供正确的值。



 a| 
SMO-14560 ：通知失败：通知配置不可用。
 a| 
通知发送失败，因为通知配置不可用。
 a| 
添加通知配置。



 a| 
SMO-14565 ：时间格式无效。请以 HH ： MM 格式输入时间格式。
 a| 
您输入的时间格式不正确。
 a| 
以 HH ： MM 格式输入时间。



 a| 
SMO-14566 ：日期值无效。有效日期范围为 1-31 。
 a| 
配置的日期不正确。
 a| 
日期应介于 1 到 31 之间。



 a| 
SMO-14567 ：日期值无效。有效日期范围为 1-7 。
 a| 
配置的日期不正确。
 a| 
输入日期范围 1 到 7 。



 a| 
SMO-14569 ：服务器无法启动摘要通知计划。
 a| 
由于未知原因， SnapManager 服务器已关闭。
 a| 
启动 SnapManager 服务器。



 a| 
SMO-14570 ：摘要通知不可用。
 a| 
您尚未配置摘要通知。
 a| 
配置摘要通知。



 a| 
SMO-14571 ：无法同时启用配置文件和摘要通知。
 a| 
您已选择配置文件和摘要通知选项。
 a| 
启用配置文件通知或摘要通知。



 a| 
SMO-14572 ：提供成功或失败通知选项。
 a| 
您尚未启用成功或失败选项。
 a| 
您必须选择成功或失败选项，或者同时选择这两者。

|===
* 相关信息 *

xref:concept_snapshot_copy_naming.adoc[Snapshot 副本命名]
