---
permalink: windows/reference_the_smosmsapclone_create_command.html 
sidebar: sidebar 
keywords: clone, create, command, backed, up, database, primary, secondary, storage, smo 
summary: 您可以运行 clone create 命令为备份的数据库创建克隆。您可以从主存储或二级存储克隆备份。 
---
= smo clone create 命令
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以运行 clone create 命令为备份的数据库创建克隆。您可以从主存储或二级存储克隆备份。



== 语法

[listing]
----

        smo clone create
-profile profile_name
[-backup-id backup_guid \| -backup-label backup_label_name \| -current\]
-newsid new_sid
\[-host target_host\]
[-label clone_label]
\[-comment string\]
-clonespec full_path_to_clonespec_file
]
\[-syspassword syspassword\]
\[-reserve \{yes \| no \| inherit\}\]

\[-no-resetlogs \| -recover-from-location path1 \[, path2\]\]\[-taskspec taskspec\]
\[-dump\]
\[-quiet \| -verbose\]
----


== Parameters

* * 配置文件名称 *
+
指定要克隆的数据库。配置文件包含数据库的标识符和其他数据库信息。

* *-backup-id guid*
+
使用指定 GUID 克隆备份。GUID 由 SnapManager 在创建备份时生成。您可以使用 smo backup list-verbose 命令显示每个备份的 GUID 。

* *-backup-label backup_laber_name*
+
指定使用指定标签名称克隆备份。

* * - 当前 *
+
指定从数据库的当前状态创建备份和克隆。

+

NOTE: 如果数据库处于 nodarchivelog 模式， SnapManager 将创建脱机备份。

* * — newsid new_sid*
+
为克隆的数据库指定一个新的唯一 Oracle 系统标识符。系统标识符值最多为八个字符。Oracle 不允许在同一主机上同时运行具有相同系统标识符的两个数据库。

* * — host target_host*
+
指定应在其上创建克隆的主机。

* * — label clone_label *
+
指定克隆的标签。

* * —注释字符串 *
+
指定用于描述此克隆的可选注释。必须将字符串用单引号括起来。

+

NOTE: 某些 shell 会删除引号。如果您的 shell 确实如此，则必须使用反斜杠（ \ ）转义引号。例如，您可能需要输入： " This is a coming\"

* *-clonSpec full_path_to_clonesore_file*
+
指定克隆规范 XML 文件的路径。此路径可以是相对路径名称，也可以是绝对路径名称。

* * — sysspassword sysspassword*
+
指定 sys 特权用户的密码。

+

NOTE: 如果为 sys 特权用户提供的数据库凭据与为 sys 特权用户提供的数据库凭据不同，则必须为 sys 特权用户提供密码。

* * —预留 *
+
将 -reserve 选项设置为 yes 可确保为新克隆卷启用卷保证空间预留。将 -reserve 选项设置为 no 可确保为新克隆卷关闭卷保证空间预留。将 -reserve 选项设置为继承可确保新克隆继承父 Snapshot 副本的空间预留特性。默认设置为 No

+
下表介绍了克隆方法及其对克隆创建操作及其 -reserve 选项的影响。可以使用任一方法克隆 LUN 。

+
|===


| 克隆方法 | Description | 结果 


 a| 
 LUN cloning a| 
 A new clone LUN is created within the same volume. a| 
 When the -reserve option for a LUN is set to yes, space is reserved for the full LUN size within the volume.


 a| 
 Volume cloning a| 
 A new FlexClone is created, and the clone LUN exists within the new clone volume. Uses the FlexClone technology. a| 
 When the -reserve option for a volume is set to yes, space is reserved for the full volume size within the aggregate.
+

|===
* *-no-resetlogs*
+
指定跳过恢复数据库，执行 DBNEWID 实用程序，并且在创建克隆时不使用重置日志打开数据库。

* * —从位置恢复 *
+
指定归档日志备份的外部归档日志位置， SnapManager 会从外部位置获取归档日志文件并使用这些文件进行克隆。

* * — taskspec*
+
指定用于克隆操作的预处理活动或后处理活动的任务规范 XML 文件。您必须提供任务规范 XML 文件的完整路径。

* * —转储 *
+
指定在克隆创建操作后收集转储文件。

* * —静默 *
+
在控制台中仅显示错误消息。默认设置为显示错误和警告消息。

* * —详细 *
+
在控制台中显示错误，警告和信息性消息。





== 示例

以下示例将使用为此克隆创建的克隆规范克隆备份：

[listing]
----
smo clone create -profile SALES1 -backup-label full_backup_sales_May -newsid
CLONE -label sales1_clone -clonespec E:\\spec\\clonespec.xml
----
[listing]
----
Operation Id [8abc01ec0e794e3f010e794e6e9b0001] succeeded.
----
* 相关信息 *

xref:task_creating_clone_specifications.adoc[正在创建克隆规范]

xref:task_cloning_databases_from_backups.adoc[从备份克隆数据库]
