---
permalink: windows/task_installing_snapmanager_for_oracle.html 
sidebar: sidebar 
keywords: install, snapmanager, host, database, manage, install 
summary: 您可以在要管理一个或多个数据库的主机上安装 SnapManager 。每个主机只能安装一个 SnapManager 实例。 
---
= 安装适用于 Oracle 的 SnapManager
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在要管理一个或多个数据库的主机上安装 SnapManager 。每个主机只能安装一个 SnapManager 实例。

* 您必须已完成所需的安装前任务。
* 必须下载最新的 SnapManager 安装包。
* 必须在所有目标主机上安装和配置适用于 Windows 的适当版本的 SnapDrive 。
+
有关安装和配置 SnapDrive for Windows 的信息，请参见 _Windows SnapDrive 安装和管理指南 _ 。

+
.. 双击 SnapManager 安装文件：
+
|===


| 操作系统 | 然后使用 ... 


 a| 
Windows x86
 a| 
netapp.smo.windows-x86-version.exe



 a| 
Windows x64
 a| 
netapp.smo.windows-x64-version.exe

|===
+
此时将显示以下消息： The publisher could not be verified.确实要运行此软件？

.. 单击 * 确定 * 。
.. 在简介窗口中，单击 * 下一步 * 。
.. 在选择安装文件夹窗口中，单击 * 下一步 * 接受默认安装位置或选择新位置。
+
默认位置为 C ： \Program Files\NetApp\SnapManager for Oracle 。

.. 在菜单可用性窗口中，单击 * 下一步 * 。
.. 在指定服务属性窗口中，输入 Windows 服务的帐户和密码信息。
+
指定帐户必须是以下组的成员：

+
*** 存储系统的本地管理组
*** 本地管理员的组
*** ORA_DBA 组，您可以指定该服务是必须在重新启动后自动启动还是应手动启动。


.. 在预安装摘要窗口中，单击 * 安装 * 。
.. 在 Install complete 窗口中，单击 * 下一步 * 。
.. 在重要信息窗口中，单击 * 完成 * 退出安装程序。




完成安装后，您可以验证安装是否成功：

. 启动 SnapManager 服务器：
+
.. 在 Windows 服务窗口中，选择 * 适用于 Oracle* 的 NetApp SnapManager 版本。
.. 在左侧面板中，单击 * 启动 * 。


. 验证 SnapManager 系统是否正常运行：
+
.. 单击 * 开始 * > * 程序 * > * NetApp * > * 适用于 Oracle* 的 SnapManager > * 启动 SMO 命令行界面（ CLI ） * 。
.. 在命令行界面（ CLI ）中，输入以下命令： smo system verify the following message is displayed ： operation ID number succeeded.


+
number 是操作 ID 编号。



* 相关信息 *

xref:concept_preparing_to_install_snapmanager_for_oracle.adoc[准备安装适用于 Oracle 的 SnapManager]

xref:concept_preinstallation_tasks.adoc[预安装任务]

xref:task_downloading_snapmanager_for_oracle_installation_package.adoc[下载适用于 Oracle 的 SnapManager 安装包]

http://mysupport.netapp.com/["NetApp 支持站点上的文档： mysupport.netapp.com"]
