---
permalink: unix-administration/concept_requirements_for_using_asm_databases_with_snapmanager.html 
sidebar: sidebar 
keywords: automatic, storage, management, asm, snapmanager, database, snapmanager, 
summary: 您必须了解将自动存储管理（ Automatic Storage Management ， ASM ）数据库与 SnapManager 结合使用的要求。了解这些要求有助于避免 ASMLib ，分区和克隆规范等方面的问题。 
---
= 将 ASM 数据库与 SnapManager 结合使用的要求
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须了解将自动存储管理（ Automatic Storage Management ， ASM ）数据库与 SnapManager 结合使用的要求。了解这些要求有助于避免 ASMLib ，分区和克隆规范等方面的问题。

* SnapManager （ 3.0.3 或更高版本）使用 Oracle 11gR2 提供的新 sysasm 特权，而不是 sysdba 特权来管理 Oracle ASM 实例。
+
如果您使用 sysdba 权限对 ASM 实例运行管理命令，则会显示一条错误消息。数据库使用 sysdba 权限访问磁盘组。如果您使用 sysasm 权限连接到 ASM 实例，则可以完全访问所有可用的 Oracle ASM 磁盘组和管理功能。

+

NOTE: 如果您使用的是 Oracle 10gR2 和 11gR1 ，则必须继续使用 sysdba 权限。

* SnapManager （ 3.0.3 或更高版本）支持备份直接存储在 ASM 磁盘组上的数据库，前提是该磁盘组还包含自动集群文件系统（ ACFS ）卷。
+
这些文件由 SnapManager 间接保护，可以使用 ASM 磁盘组的其余内容进行还原，但 SnapManager （ 3.0.3 或更高版本）不支持 ACFS 。

+

NOTE: ACFS 是 Oracle 11gR2 提供的一种多平台，可扩展的文件系统存储管理技术。ACFS 扩展了 ASM 功能，可支持在 Oracle 数据库外部维护的客户文件。

* 如果 SnapManager （ 3.0.3 或更高版本）磁盘组还包含 Oracle 集群注册表（ Oracle Cluster Registry ， OCR ）文件或表决磁盘文件，则支持备份存储在 ASM 磁盘组上的文件；但是，还原操作需要使用速度较慢，基于主机或部分文件快照还原（ PFSR ）方法。
+
最好在不包含数据库文件的磁盘组上使用 OCR 和投票磁盘。

* 用于 ASM 的每个磁盘只能包含一个分区。
* 托管 ASM 数据的分区必须正确对齐，以避免出现严重的性能问题。
+
这意味着 LUN 的类型必须正确，分区的偏移量必须为 4 k 字节的倍数。

+

NOTE: 有关如何创建与 4K 对齐的分区的详细信息，请参见知识库文章 1010717 。

* 未在克隆规范中指定 ASM 配置。
+
在将主机升级到 SnapManager （ 2.2 或更高版本）之前，您必须手动删除使用 SnapManager 2.1 创建的克隆规范中的 ASM 配置信息。

* SnapManager 3.1 ， 3.1p1 和 3.2 或更高版本支持 ASMLib 2.1.4 。
* SnapManager 3.1p4 或更高版本支持 ASMLib 2.1.4 ， 2.1.7 和 2.1.8 。

