---
permalink: unix-administration/reference_the_smosmsap_notification_updatesummarynotification_command.html 
sidebar: sidebar 
keywords: run, notification, update-summary-notification, command, summary, enable, repository, database, smo 
summary: 您可以运行 notification update-summary-notification 命令为存储库数据库启用摘要通知。 
---
= smo notification update-summary-notification 命令
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以运行 notification update-summary-notification 命令为存储库数据库启用摘要通知。



== 语法

[listing]
----

        smo notification update-summary-notification
-repository
-port repo_port
-dbname  repo_service_name
-host repo_host
-login -username repo_username
-email email-address1,email-address2
-subject subject-pattern
-frequency
[-daily –time daily_time \|
-hourly –time hourly_time \|
-monthly –time monthly_time -date \[1\|2\|3\|...\|31\] \|
-weekly  –time weekly_time -day \[1\|2\|3\|4\|5\|6\|7\]\]
-profiles profile1,profile2
-notification-host notification-host
\[-quiet \| -verbose\]
----


== Parameters

* * 存储库 *
+
指定存储库数据库的详细信息。

* * 端口 repo_port*
+
指定用于访问存储库数据库的 TCP 端口号。

* * — dbname repo_service_name*
+
指定存储库数据库的名称。您可以使用全局名称或系统标识符。

* * — host repo_host*
+
指定存储库数据库所在主机的名称或 IP 地址。

* * —登录 *
+
指定存储库登录详细信息。这是可选的。如果未指定，则 SnapManager 默认为操作系统身份验证连接模式。

* * 用户名 repo_username*
+
指定访问存储库数据库所需的用户名。

* 电子邮件电子邮件地址 1 ，电子邮件地址 2 *
+
指定收件人的电子邮件地址。

* * 主题主题模式 *
+
指定电子邮件主题模式。

* * 频率 ｛ -daily -time daily _time | -hourly -time hourly_time | -monthly -time monthly_time -date ｛ 1|2|3...-31 ｝ _ - 每周 - 时间 weekly_time -Day ｛ 1|2|3|4|5|6|7 ｝ *
+
指定希望电子邮件通知的计划类型和计划时间。

* * 配置文件 profile1 ， profile2*
+
指定需要电子邮件通知的配置文件名称。

* * — notification — host notification — host*
+
指定将摘要通知电子邮件发送到收件人的 SnapManager 服务器主机。您可以为通知主机提供主机名或 IP 地址。您还可以更新主机 IP 或主机名。

* * —静默 *
+
在控制台中仅显示错误消息。默认情况下会显示错误和警告消息。

* * —详细 *
+
在控制台中显示错误，警告和信息性消息。





== 示例

以下示例将为存储库数据库启用摘要通知：

[listing]
----

smo notification update-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5 –email admin@org.com –subject success –frequency -daily -time 19:30:45 –profiles sales1
----