---
permalink: unix-administration/reference_product_overview.html 
sidebar: sidebar 
keywords: snapmirror, oracle, automate, simplifies, complex, manual, time-consuming, process, backup, recover, clone, technologies, aoracle, real, application, clusters, rac 
summary: SnapManager for Oracle 可自动执行和简化与 Oracle 数据库的备份，恢复和克隆相关的复杂，手动且耗时的流程。您可以使用采用 ONTAP SnapMirror 技术的 SnapManager 在另一个卷上创建备份副本，并使用 ONTAP SnapVault 技术将备份高效归档到磁盘。 
---
= 产品概述
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for Oracle 可自动执行和简化与 Oracle 数据库的备份，恢复和克隆相关的复杂，手动且耗时的流程。您可以使用采用 ONTAP SnapMirror 技术的 SnapManager 在另一个卷上创建备份副本，并使用 ONTAP SnapVault 技术将备份高效归档到磁盘。

SnapManager 可与原生 Oracle 技术集成，例如 Oracle Real Application Clusters （ Oracle RAC ），自动存储管理（ ASM ）以及跨 FC ， iSCSI 和 NFS 协议的直接 NFS 。或者，可以使用 Oracle 恢复管理器（ RMAN ）对使用 SnapManager 创建的备份进行编目，以保留备份信息；这些备份可稍后用于块级还原或表空间时间点恢复操作。



== SnapManager 亮点

SnapManager 可与 UNIX 主机上的 Oracle 数据库以及后端的 NetApp Snapshot ， SnapRestore 和 FlexClone 技术无缝集成它提供了易于使用的用户界面（ UI ）以及用于管理功能的命令行界面（ CLI ）。

使用 SnapManager ，您可以执行以下数据库操作并高效管理数据：

* 在主存储或二级存储上创建节省空间的备份
+
您可以单独备份数据文件和归档日志文件。

* 计划备份
* 使用基于文件或基于卷的还原操作还原完整或部分数据库
* 通过从备份中发现，挂载和应用归档日志文件来恢复数据库
* 仅为归档日志创建备份时，从归档日志目标中删除归档日志文件
* 通过仅保留包含唯一归档日志文件的备份，自动保留最少数量的归档日志备份
* 跟踪操作详细信息并生成报告
* 验证备份以确保备份采用有效的块格式，并且备份的文件均未损坏
* 维护对数据库配置文件执行的操作的历史记录
+
配置文件包含有关要由 SnapManager 管理的数据库的信息。

* 在主存储系统或二级存储系统上为备份创建节省空间的克隆
+
使用 SnapManager 可以拆分数据库的克隆。


