---
permalink: unix-administration/task_restoring_backups_from_secondary_storage.html 
sidebar: sidebar 
keywords: restore, protect, backup, secondary, storage, copy, data, primary, storage 
summary: 您可以从二级存储还原受保护的备份，并选择将数据复制回主存储的方式。 
---
= 从二级存储还原备份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从二级存储还原受保护的备份，并选择将数据复制回主存储的方式。

您可以使用带有 -from-secondary 选项的 backup restore 命令从二级存储还原数据。如果未指定 -from-secondary 选项，则 SnapManager 将从主存储上的 Snapshot 副本还原数据。

如果备份位于主存储上，则不能使用 -from-secondary 选项；必须先释放主备份，然后才能从二级存储还原备份。如果使用临时卷，则必须使用 -temp-volume 选项指定此卷。

每当指定 -from-secondary 选项时，都必须指定 -copy-id 选项。如果二级存储系统上有多个备份，则使用 -copy-id 选项指定二级存储上的哪个备份副本应用于还原操作。


NOTE: 如果您使用的是在 7- 模式下运行的 Data ONTAP ，则必须为 -copy-id 选项指定有效值。但是，如果使用的是集群模式 Data ONTAP ，则不需要 -copy-id 选项。

从二级存储还原数据时， SnapManager 会首先尝试将数据直接从二级存储系统还原到主存储系统（而不涉及主机）。如果 SnapManager 无法执行此类还原（例如，如果文件不属于文件系统），则 SnapManager 将回退到主机端文件副本还原。SnapManager 可通过两种方法从二级存储执行主机端文件副本还原。SnapManager 选择的方法在 SMO.config 文件中进行配置。

* 如果 restore.secondaryAccessPolicy = Direct ，则 SnapManager 会克隆二级存储上的数据，将克隆的数据从二级存储系统挂载到主机，然后将数据从克隆复制到活动环境。
+
这是默认的二级访问策略。

* 如果 restore.secondaryAccessPolicy = 间接，则 SnapManager 会首先将数据复制到主存储上的临时卷，将数据从临时卷挂载到主机，然后将数据从临时卷复制到活动环境。
+
只有当主机无法直接访问二级存储系统时，才应使用此策略。使用间接方法恢复所需时间是直接方法的两倍，因为会创建两个数据副本。

+
.. 执行以下操作之一：
+
|===
| 如果您要 ... | 那么 ... 


 a| 
如果选定备份位于主存储上，请还原完整的数据库
 a| 
输入以下命令： smo backup restore -profileprofile_name-labelLabel-complete-recover -alllogs[-copy-idi]



 a| 
如果选定备份不在主存储上，请还原完整的数据库
 a| 
输入以下命令： smo backup restore -profileprofileprofile_name-labelLabel-complete-recover -alllogs-from-secondary （ -temp-volume <temp_volume>] ）（ -copy-ididid ）

|===






== 示例

以下命令将从二级存储系统还原受保护的备份：

[listing]
----
smo backup restore -profile PAYDB -label daily_monday -complete
-recover alllogs -from-secondary -copy-id 3042 -temp-volume smo_scratch_restore_volume
Operation Id [8abc011215d385920115d38599470001] succeeded.
----