---
permalink: unix-administration/task_customizing_the_email_subject_for_an_existing_profile.html 
sidebar: sidebar 
keywords: snapmanager, enable, customize, email, subject, pattern, exist, profile, smo 
summary: 通过 SnapManager ，您可以通过更新现有配置文件来自定义该配置文件的电子邮件主题模式。此自定义主题模式仅适用于更新后的配置文件。 
---
= 自定义现有配置文件的电子邮件主题
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 SnapManager ，您可以通过更新现有配置文件来自定义该配置文件的电子邮件主题模式。此自定义主题模式仅适用于更新后的配置文件。

. 输入以下命令： smo profile update -profileprofile "-profile-passwordprofile_password]] ｛ -database-dbnamedb_dbname-host db_host "-siddb_sid] ｛ -login -usernamedb_username-password db_password-port db_port]] ｛ -groupm ｛ -controlfile _ ｛ -group-snap-name]-snap-snap-snap-name]-snap-snap-snap-name]-snap-man-snap-snap-snap-name]-snap-snap-snap-snap-snapmirrorings1<-snap-snap-snap-snap-snap-snap-snap-name]<-snap-snap-snap-snap-snap-snap-snap-snap-name]-snap-snap-snap-snap-snap-snap-snap-snap-name]-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-name]-snap-snap-snapmirrorings1<-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-name]


以下示例显示了电子邮件主题模式：

[listing]
----

smo profile update -profile sales1 -profile-password sales1 -repository -dbname repo2 -host 10.72.197.133 -port 1521 -login -username admin2 -database -dbname DB1 -host 10.72.197.142 -sid DB1
-osaccount oracle -osgroup dba -profile-notification -success -email admin@org.com -subject {profile}_{operation-name}_{db-sid}_{db-host}_{start-date}_{end-date}_{status}
----