---
permalink: unix-administration/task_using_snapmanager_for_oracle_to_create_the_database_profile_and_assign_a_protection_policy.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, oracle, enable, protect, client, payroll, paydb 
summary: 您必须在 SnapManager for Oracle 中创建配置文件，在配置文件中启用保护，并分配保护策略以创建受保护的备份。 
---
= 使用 SnapManager for Oracle 创建数据库配置文件并分配保护策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须在 SnapManager for Oracle 中创建配置文件，在配置文件中启用保护，并分配保护策略以创建受保护的备份。

配置文件包含有关所管理数据库的信息，包括其凭据，备份设置和备份保护设置。创建配置文件后，您无需在每次执行操作时指定数据库详细信息。一个配置文件只能引用一个数据库，但同一个数据库可以由多个配置文件引用。

. 转到 SnapManager for Oracle 客户端。
. 从存储库树中，右键单击主机，然后选择 * 创建配置文件 * 。
. 在配置文件配置信息页面上，输入配置文件详细信息，然后单击 * 下一步 * 。
+
您可以输入以下信息：

+
** 配置文件名称： paying_prod2
** 配置文件密码： payroll123
** 注释：生产薪资数据库


. 在数据库配置信息页面上，输入数据库详细信息，然后单击 * 下一步 * 。
+
您可以输入以下信息：

+
** 数据库名称： PAYDB
** 数据库 SID ： payrolldb
** Database host ：接受默认值。由于您要从存储库树中的主机创建配置文件，因此 SnapManager 会显示主机名。
** 主机帐户，表示 Oracle 用户帐户： oracle
** 主机组，表示 Oracle 组： DBA


. 在数据库连接信息页面上，单击 * 使用数据库身份验证 * 以允许用户使用数据库信息进行身份验证。
. 输入数据库连接详细信息并单击 * 下一步 * 。
+
您可以输入以下信息：

+
** sysdba 特权用户名，表示具有管理权限的系统数据库管理员： sys
** 密码（ SYSDBA 密码）： Oracle
** 用于连接到数据库主机的端口： 1521.


. 在 RMAN 配置信息页面上，单击 * 不使用 RMAN* ，然后单击 * 下一步 * 。
+
Oracle Recovery Manager （ RMAN ）是一款 Oracle 工具，可帮助您使用块级检测来备份和恢复 Oracle 数据库。

. 在 Snapshot Naming Information 页面上，通过选择变量为与此配置文件关联的 Snapshot 指定命名约定。
+
SMID 变量创建唯一的快照标识符。

+
执行以下操作：

+
.. 在 Variable Token 列表中，选择 usertext 并单击 * 添加 * 。
.. 输入 payroll.techco.com 作为主机名，然后单击 * 确定 * 。
.. 单击 * 左侧 * ，直到主机名显示在 "Format" （格式）框中 SMO 之后。
.. 单击 * 下一步 * 。


+
SMO_hostname_smoprofile_dbsid_scope_mode_smID 的 Snapshot 命名约定为 smo_payroll.techco.com_payroll_prod2_payrolldb_f_a_x" （其中， "f" 表示完整备份， "A" 表示自动模式， "x" 表示唯一的 SMID ）。

. 选择 * 保护管理器保护策略 * 。
+
使用 * Protection Manager Protection Policy* ，您可以选择使用 NetApp 管理控制台配置的保护策略。

. 从从 NetApp 管理控制台检索到的保护策略中选择 * 技术公司薪资数据：备份 * 作为保护策略，然后单击 * 下一步 * 。
. 在 Perform Operation 页面上，验证信息并单击 * 创建 * 。
. 单击 * 操作详细信息 * 可查看有关配置文件创建操作和基于卷的还原资格信息。
+
** 将 NetApp 管理控制台保护策略分配给数据库配置文件会自动创建一个非一致数据集，此数据集可由 NetApp 管理控制台操作员查看，并使用名称约定 SMO_<hostname>_<profilename> 或在本示例中为 smo_payroll.tech.com_PAYDB 。
** 如果此配置文件不符合卷还原条件（也称为 " 快速还原 " ），则会发生以下情况：
+
*** "* 结果 * " 选项卡表示配置文件创建成功，并且在操作期间出现警告。
*** "* 操作详细信息 * " 选项卡包含一个警告日志，其中指出配置文件不符合快速还原的条件并解释了原因。





