---
permalink: unix-administration/task_creating_profiles.html 
sidebar: sidebar 
keywords: creating, profile, assign, particular, oracle, database, user, account 
summary: 创建配置文件时，您可以为此配置文件分配特定的 Oracle 数据库用户帐户。您可以为配置文件设置保留策略，为使用此配置文件的所有备份启用对二级存储的备份保护，以及为每个保留类设置保留计数和持续时间。 
---
= 正在创建配置文件
:icons: font
:imagesdir: ../media/


[role="lead"]
创建配置文件时，您可以为此配置文件分配特定的 Oracle 数据库用户帐户。您可以为配置文件设置保留策略，为使用此配置文件的所有备份启用二级存储备份保护，以及为每个保留类设置保留计数和持续时间。

如果不提供数据库的 -login ， -password 和 -port 参数值，则操作系统（ OS ）身份验证模式将使用默认凭据。

创建配置文件时， SnapManager 会执行还原资格检查，以确定可用于还原数据库的还原机制。如果数据库位于 qtree 上，并且父卷不符合快速或基于卷的还原条件，则分析可能会出错。

通过 SnapManager （ 3.2 或更高版本），您可以在创建新配置文件或更新现有配置文件时将归档日志文件与数据文件分开。使用配置文件分离备份后，您可以仅创建数据库的数据文件备份或归档日志备份。您可以使用新配置文件或更新后的配置文件创建包含数据文件和归档日志文件的备份。但是，您不能使用配置文件创建完整备份或还原设置。

* 用于创建完整备份和部分备份的配置文件 *

您可以创建配置文件来创建完整的数据库备份，其中包含数据文件，控制文件和归档日志文件，以及包含指定数据文件或表空间，所有控制文件和所有归档日志文件的部分数据库备份。SnapManager 不允许使用为完整备份和部分备份创建的配置文件创建单独的归档日志备份。

* 用于创建仅数据文件备份和仅归档文件备份的配置文件 *

创建新配置文件时，您可以包括 -separate archivelog-backups ，以便将归档日志备份与数据文件备份分开。您还可以更新现有配置文件，以便将归档日志备份与数据文件备份分开。

通过使用新的配置文件选项分隔归档日志备份，您可以执行以下 SnapManager 操作：

* 创建归档日志备份
* 删除归档日志备份
* 挂载归档日志备份
* 释放归档日志备份


创建配置文件以将归档日志备份与数据文件备份分开时，如果创建该配置文件的数据库中不存在归档日志文件，则活动文件系统中不存在警告消息归档日志文件。此时将显示早于 <archive log threaded version> 日志文件的归档日志文件版本不会包含在备份中。即使为此数据库创建备份，归档日志文件也不会在数据库备份中可用。


NOTE: 如果在创建配置文件时遇到错误，请使用 smsystem dump 命令。创建配置文件后，如果遇到错误，请使用 smooperation dump 和 smoprofile dump 命令。

. 要使用用户名，密码和端口（ Oracle 身份验证）创建配置文件，请输入以下命令： smo profile create -profileprofile "-profile-passwordprofile_password] -repositor-dbnamerepo_dbname-host-host-portrepo_port-login-usernamerepo_username-database-dbnamedb_dbname-hostdb_host "-siderdb_sider_dsb] -login （ -userwordynms-username ） [-snap-snap-man-snap-snap-name
+
此命令的其他选项如下：

+
'-force]-noprompt]'

+
'[ 静默 > 详细信息 ]'

+

NOTE: 对于 Real Application Clusters （ RAC ）环境，在创建新配置文件时，必须将 db_unique_name 参数的值提供为 db_dbname 。

+
在创建配置文件时，您还可以根据要访问数据库的方式包括其他选项。

+
|===


| 条件 | 那么 ... 


 a| 
* 您希望使用操作系统身份验证来创建配置文件 *
 a| 
为 DBA 组中的操作系统帐户指定变量（通常是用于安装 Oracle 的帐户）。请指定以下内容，而不是添加用户名，密码和端口：

** -osaccountaccountaccount_name 作为操作系统帐户的名称
** -osgroupos 组作为与操作系统帐户关联的组




 a| 
* 要使用自动存储管理（ Automatic Storage Management ， ASM ）实例身份验证来创建配置文件 *
 a| 
指定 ASM 实例身份验证的凭据。

** -asmusernameasmintation_username 是用于登录到 ASM 实例的用户名。
** -asmpasswordasminstance_password 是用于登录到 ASM 实例的密码。




 a| 
* 要使用数据库身份验证创建配置文件 *
 a| 
指定数据库登录详细信息。如果密码包含感叹号（！），美元符号（ $ ）或重音符（` ）等特殊字符，则 SnapManager 不允许您从命令行界面（ CLI ）创建经过数据库身份验证的配置文件。



 a| 
* 您正在使用目录作为 Oracle Recovery Manager （ RMAN ）存储库 *
 a| 
指定以下选项和变量：

** -tnsnametnssname 作为 tnsnames.ora 文件中定义的 tnsnamname 。
** -login -usernameusername 作为连接到 RMAN 目录所需的用户名。
+
如果未指定， SnapManager 将使用操作系统身份验证信息。您不能对 RAC 数据库使用操作系统身份验证。

** -passwordpassword 作为连接到 RMAN 目录所需的 RMAN 密码。




 a| 
* 您正在使用控制文件作为 RMAN 存储库 *
 a| 
指定 -controlfile 选项。



 a| 
* 您要为备份指定备份保留策略 *
 a| 
指定保留类的保留计数或持续时间，或者同时指定这两者。持续时间以类的单位为单位（例如，小时表示每小时，天表示每天）。

** -hourly 是每小时保留类，其中，（ -count n ）（ -duration m ）分别是保留计数和保留持续时间。
** -daily 是每日保留类，其保留计数和保留持续时间分别为 "-count n] 和 -durationm] 。
** -weekly 是每周保留类，其中，（ -count n] 个（ -duration m ）分别是保留计数和保留持续时间。
** -monthly 是每月保留类别，其中，（ -count n] 个（ -durationm ）分别是保留计数和保留期限。




 a| 
* 您要为配置文件启用备份保护 *
 a| 
指定以下选项和变量：

** -protect 用于启用备份保护。
+
如果您使用的是在 7- 模式下运行的 Data ONTAP ，则此选项会在 Data Fabric Manager （ DFM ）服务器中创建一个应用程序数据集，并添加与数据库，数据文件，控制文件和归档日志相关的成员。如果数据集已存在，则在创建配置文件时会重复使用同一数据集。

** 使用 -protection-policy policy 可以指定保护策略。
+
如果您使用的是在 7- 模式下运行的 Data ONTAP ，并且 SnapManager 与 Protection Manager 集成在一起，则必须指定其中一个 Protection Manager 策略。

+

NOTE: 要列出可能的保护策略，请使用 smo protection-policy list 命令。

+
如果您使用的是集群模式 Data ONTAP ，则必须选择 _SnapManager_cDOT_Mirror_ 或 _SnapManager_cDOT_Vault_Vault 。

+

NOTE: 在以下情况下，配置文件创建操作失败：

+
*** 如果您使用的是集群模式 Data ONTAP ，但选择保护管理器策略
*** 如果您使用的是在 7- 模式下运行的 Data ONTAP ，但选择 _SnapManager_cDOT_Mirror_ 或 _SnapManager_cDOT_Vault_policy
*** 如果您创建了 SnapMirror 关系，但选择了 _SnapManager_cDOT_Vault_policy 或创建了 SnapVault 关系，但选择了 _SnapManager_cDOT_Mirror_ 策略
*** 如果尚未创建 SnapMirror 或 SnapVault 关系，但选择了 _SnapManager_cDOT_Vault_or _SnapManager_cDOT_Mirror_ 策略


** -noprotect 表示不保护使用配置文件创建的数据库备份。* 注： * 如果指定 -protect 时未指定 -protection-policy ，则数据集将没有保护策略。如果在创建配置文件时指定了 -protect 且未设置 -protection-policy ，则可以稍后通过 smo profile update 命令进行设置，也可以由存储管理员使用 Protection Manager 控制台进行设置。




 a| 
* 您希望为数据库操作的完成状态启用电子邮件通知 *
 a| 
指定以下选项和变量：

** 使用 -summary-notification ，您可以为存储库数据库下的多个配置文件配置摘要电子邮件通知。
** notification 用于接收有关配置文件数据库操作完成状态的电子邮件通知。
** 通过 -success-emailemailemail_address2 ，您可以收到有关使用新配置文件或现有配置文件成功执行数据库操作的电子邮件通知。
** 通过 -failure-emailemailemail_address2 ，您可以收到有关使用新配置文件或现有配置文件执行的数据库操作失败的电子邮件通知。
** -subjectsubject_text 指定创建新配置文件或现有配置文件时电子邮件通知的主题文本。如果未为此存储库配置通知设置，而您尝试使用命令行界面配置配置文件或摘要通知，则控制台日志中会记录以下消息： "MO-14577： Notification Settings not configureed" 。
+
如果您已配置通知设置，并尝试使用命令行界面配置摘要通知，但未启用存储库的摘要通知，则控制台日志中会显示以下消息： "MO-14575 ： summary notification configuration not available for this repository______"





 a| 
* 您希望将归档日志文件与数据文件分开备份 *
 a| 
指定以下选项和变量：

** 使用 -separate archivelog-backups 可以将归档日志备份与数据文件备份分开。
** -retain-archivelog-backups 用于设置归档日志备份的保留期限。您必须指定正保留期限。
+
归档日志备份会根据归档日志保留期限进行保留。数据文件备份会根据现有保留策略进行保留。

** -protect 用于保护归档日志备份。
** -protection-policy 将保护策略设置为归档日志备份。
+
归档日志备份会根据归档日志保护策略进行保护。数据文件备份会根据现有保护策略进行保护。

** -include-with 联机备份包括归档日志备份以及联机数据库备份。
+
通过此选项，您可以同时创建联机数据文件备份和归档日志备份以进行克隆。如果设置了此选项，则每当创建联机数据文件备份时，都会立即创建归档日志备份以及数据文件。

** -no-include-with 联机备份不包括归档日志备份和数据库备份。




 a| 
* 您可以在成功执行配置文件创建操作 * 后收集转储文件
 a| 
在 profile create 命令的末尾指定 -dump 选项。

|===
+
创建配置文件时， SnapManager 会分析这些文件，以备日后需要对配置文件中指定的文件执行基于卷的还原操作时使用。



* 相关信息 *

xref:concept_how_to_collect_dump_files.adoc[如何收集转储文件]
