---
permalink: unix-administration/task_setting_role-based_access_control_capabilities_and_roles.html 
sidebar: sidebar 
keywords: enable, role-based, access, control, rbac, snapmanager, snapdrive, capabilities, role, smo 
summary: 在使用 SnapDrive 为 SnapManager 启用基于角色的访问控制（ RBAC ）后，您可以将 RBAC 功能和用户添加到角色以执行 SnapManager 操作。 
---
= 设置基于角色的访问控制功能和角色
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用 SnapDrive 为 SnapManager 启用基于角色的访问控制（ Role-Based Access Control ， RBAC ）后，您可以向角色添加 RBAC 功能和用户以执行 SnapManager 操作。

您必须在 Data Fabric Manager 服务器中创建一个组，并将该组添加到主存储系统和二级存储系统。运行以下命令：

* dfm group create smo_grp
* dfm group add smo_grpprimary_storage_system
* dfm group add smo_grpsecondary _storage_system


您可以使用 Operations Manager Web 界面或 Data Fabric Manager 服务器命令行界面（ CLI ）来修改 RBAC 功能和角色。

下表列出了执行 SnapManager 操作所需的 RBAC 功能：

|===
| SnapManager 操作 | 未启用数据保护时所需的 RBAC 功能 | 启用数据保护时所需的 RBAC 功能 


 a| 
配置文件创建或配置文件更新
 a| 
sd.Storage.Read （ SMO_grp ）
 a| 
sd.Storage.Read （ SMO_PROFILE 数据集）



 a| 
配置文件保护
 a| 
dfm.Database.Write （ SMO_grp ）

sd.Storage.Read （ SMO_grp ）

sd.Config.Read （ SMO_grp ）

sd.Config.Write （ SMO_grp ）

sd.Config.Delete （ SMO_grp ）

GlobalDataProtection
 a| 
无



 a| 
创建备份
 a| 
sd.Storage.Read （ SMO_grp ）

sd.Snapshot.Write （ SMO_grp ）

sd.Snapshot.Read （ SMO_grp ）

sd.Snapshot.Delete （ SMO_grp ）
 a| 
sd.Storage.Read （ SMO_PROFILE 数据集）

sd.Snapshot.Write （ SMO_PROFILE 数据集）

sd.Snapshot.Read （ SMO_profile 数据集）

sd.Snapshot.Delete （ SMO_PROFILE 数据集）



 a| 
备份创建（使用 DBverify ）
 a| 
sd.Storage.Read （ SMO_grp ）

sd.Snapshot.Write （ SMO_grp ）

sd.Snapshot.Read （ SMO_grp ）

sd.Snapshot.Delete （ SMO_grp ）

sd.snapshot.Clone （ SMO_grp ）
 a| 
sd.Storage.Read （ SMO_PROFILE 数据集）

sd.Snapshot.Write （ SMO_PROFILE 数据集）

sd.Snapshot.Read （ SMO_profile 数据集）

sd.Snapshot.Delete （ SMO_PROFILE 数据集）

sd.snapshot.Clone （ SMO_profile 数据集）



 a| 
备份创建（使用 RMAN ）
 a| 
sd.Storage.Read （ SMO_grp ）

sd.Snapshot.Write （ SMO_grp ）

sd.Snapshot.Read （ SMO_grp ）

sd.Snapshot.Delete （ SMO_grp ）

sd.snapshot.Clone （ SMO_grp ）
 a| 
sd.Storage.Read （ SMO_PROFILE 数据集）

sd.Snapshot.Write （ SMO_PROFILE 数据集）

sd.Snapshot.Read （ SMO_profile 数据集）

sd.Snapshot.Delete （ SMO_PROFILE 数据集）

sd.snapshot.Clone （ SMO_profile 数据集）



 a| 
备份还原
 a| 
sd.Storage.Read （ SMO_grp ）

sd.Snapshot.Write （ SMO_grp ）

sd.Snapshot.Read （ SMO_grp ）

sd.Snapshot.Delete （ SMO_grp ）

sd.snapshot.Clone （ SMO_grp ）

sd.Snapshot.Restore （ SMO_grp ）
 a| 
sd.Storage.Read （ SMO_PROFILE 数据集）

sd.Snapshot.Write （ SMO_PROFILE 数据集）

sd.Snapshot.Read （ SMO_profile 数据集）

sd.Snapshot.Delete （ SMO_PROFILE 数据集）

sd.snapshot.Clone （ SMO_profile 数据集）

sd.Snapshot.Restore （ SMO_PROFILE 数据集）



 a| 
备份删除
 a| 
sd.Snapshot.Delete （ SMO_grp ）
 a| 
sd.Snapshot.Delete （ SMO_PROFILE 数据集）



 a| 
备份验证
 a| 
sd.Storage.Read （ SMO_grp ）

sd.Snapshot.Read （ SMO_grp ）

sd.Snapshot.Clone （ SMO_grp ）
 a| 
sd.Storage.Read （ SMO_PROFILE 数据集）

sd.Snapshot.Read （ SMO_profile 数据集）

sd.Snapshot.Clone （ SMO_PROFILE 数据集）



 a| 
备份挂载
 a| 
sd.Storage.Read （ SMO_grp ）

sd.Snapshot.Read （ SMO_grp ）

sd.Snapshot.Clone （ SMO_grp ）
 a| 
sd.Storage.Read （ SMO_PROFILE 数据集）

sd.Snapshot.Read （ SMO_profile 数据集）

sd.Snapshot.Clone （ SMO_PROFILE 数据集）



 a| 
备份卸载
 a| 
sd.Snapshot.Clone （ SMO_grp ）
 a| 
sd.Snapshot.Clone （ SMO_PROFILE 数据集）



 a| 
克隆创建
 a| 
sd.Storage.Read （ SMO_grp ）

sd.Snapshot.Read （ SMO_grp ）

sd.snapshot.Clone （ SMO_grp ）
 a| 
sd.Storage.Read （ SMO_PROFILE 数据集）

sd.Snapshot.Read （ SMO_profile 数据集）

sd.snapshot.Clone （ SMO_profile 数据集）



 a| 
克隆删除
 a| 
sd.Snapshot.Clone （ SMO_grp ）
 a| 
sd.Snapshot.Clone （ SMO_PROFILE 数据集）



 a| 
克隆拆分
 a| 
sd.Storage.Read （ SMO_grp ）

sd.Snapshot.Read （ SMO_grp ）

sd.snapshot.Clone （ SMO_grp ）

sd.Snapshot.Delete （ SMO_grp ）

sd.Storage.Write （ SMO_GRP ）
 a| 
sd.Storage.Read （ SMO_PROFILE 数据集）

sd.Snapshot.Read （ SMO_profile 数据集）

sd.snapshot.Clone （ SMO_profile 数据集）

sd.Snapshot.Delete （ SMO_PROFILE 数据集）

sd.Storage.Write （ SMO_PROFILE 数据集）

|===
有关定义 RBAC 功能的详细信息，请参见 _Unified Manager OnCommand 操作管理器管理指南 _ 。

. 访问 Operations Manager 控制台。
. 从设置菜单中，选择 * 角色 * 。
. 选择一个现有角色或创建一个新角色。
. 要为数据库存储资源分配操作，请单击 * 添加功能 * 。
. 在编辑角色设置页面上，要保存对角色所做的更改，请单击 * 更新 * 。


* 相关信息 *

http://support.netapp.com/documentation/productsatoz/index.html["_OnCommand Unified Manager Operations Manager Administration Guide_: [mysupport.netapp.com/documentation/productsatoz/index.html\](https://mysupport.netapp.com/documentation/productsatoz/index.html)"]
