---
permalink: unix-installation-7mode/delete_concept_how_to_send_comments_about_documentation_and_receiv.html 
sidebar: sidebar 
keywords: doccomment, quality, documentation, high-quality, improve, quality, send, feedback, automatic, notification, production-level, document 
summary: You can help us to improve the quality of our documentation by sending us your feedback.首次发布生产级 \ （ GA/FCS\ ）文档或对现有生产级文档进行重要更改时，您可以收到自动通知。 
---
= How to send comments about documentation and receive update notifications
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
You can help us to improve the quality of our documentation by sending us your feedback.You can receive automatic notification when production-level (GA/FCS) documentation is initially released or important changes are made to existing production-level documents.

如果您对改进本文档有任何建议，请通过电子邮件将您的意见发送给我们 link:mailto:doccomments@netapp.com["doccomments@netapp.com"]。To help us direct your comments to the correct division, include in the subject line the product name, version, and operating system.

If you want to be notified automatically when production-level documentation is released or important changes are made to existing production-level documents, follow Twitter account @NetAppDoc.

You can also contact us in the following ways:

* NetApp, Inc., 495 East Java Drive, Sunnyvale, CA 94089 U.S.
* 电话： +1 （ 408 ） 822-6000
* 传真： +1 （ 408 ） 822-4501
* 支持电话： +1 （ 888 ） 463-8277

