---
permalink: unix-installation-7mode/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark 
summary: Trademark information 
---
= Trademark information
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


NetApp、 NetApp徽标、Go Further、Faster、 AltaVault、ASUP、 AutoSupport、Campaign Express、Cloud ONTAP、Clustered Data ONTAP、Customer Fitness、 Data ONTAP、DataMotion、Fitness、 Flash Accel、Flash Cache、Flash Pool、FlashRay、 FlexCache、 FlexClone、 FlexPod、FlexScale、FlexShare、 FlexVol、FPolicy、GetSuccessful、LockVault、Manage ONTAP、Mars、 MetroCluster、 MultiStore、 NetApp Insight、 OnCommand、 ONTAP、ONTAPI、 RAID DP、 RAID-TEC、 SANtricity、 SecureShare、Simplicity、Simulate ONTAP、Snap Creator、 SnapCenter、 SnapCopy、 SnapDrive、 SnapIntegrator、 SnapLock、 SnapManager、 SnapMirror、 SnapMover SnapProtect、 SnapRestore、Snapshot、 SnapValidator、 SnapVault、 StorageGRID、 Tech OnTap、Unbound Cloud、 WAFL和其他名称是NetApp, Inc. 在美国和/或其他国家/地区的商标或注册商标。所有其他品牌或产品均为其各自所有者的商标或注册商标，应予同样对待。  NetApp商标的最新列表可在以下网址找到： http://www.netapp.com/us/legal/netapptmlist.aspx[] 。
